# All paths are relative to the root of the repository. Use forward slashes as separators, they will work on Windows as well.
# Traversing up is supported. Use ".." in the path to go up a directory.

[paths]
input_images = 'CHRL_data'
labels = 'CHRL_data/labels.csv'
pole_metadata = 'CHRL_data/pole_metadata.csv'
trainee_model = '' #TODO
images_output = 'C:\Users\pawsonk\Coastal Hydrology\output\images'
models_output = 'C:\Users\pawsonk\Coastal Hydrology\output\models'

[labeling]
subset_to_label = 100 # Label every N images
number_of_poles = 3

[training]
lr = 0.001 # Learning Rate 
epochs = 200 # Epochs
aug = false # whether to augment the data or not

device = "cpu" # Device to use, either "cuda" or "cpu".

batch_size = 8 # Batch size
show_dataset_plot = false # Show dataset plot
filter = false