# ====================================
# PATHS Configuration
# All paths are relative to the root of the repository. Use forward slashes as separators, they will work on Windows as well.
# Traversing up is supported. Use ".." in the path to go up a directory.
# ====================================
[paths]
input_images = 'CHRL_data/sites'
labels = 'CHRL_data/labels.csv'
pole_metadata = 'CHRL_data/pole_metadata.csv'

# Model paths
pretrained_model = "models/CO_and_WA_model.pth" # Breen's existing model
trained_model_name = "model.pth"
models_output = 'C:\Users\pawsonk\Coastal Hydrology\output\models'
images_output = 'C:\Users\pawsonk\Coastal Hydrology\output\images'

# ====================================
# LABELING Configuration
# ====================================
[labeling]
#Higher target count has better accuracy but takes longer to label
target_label_count = 40 # The total amount of images to label per site

# ====================================
# TRAINING Configuration
# ====================================
[training]
lr = 0.0001 # Learning Rate
epochs = 200 # Epochs
batch_size = 8 # Batch size
aug = true # whether to augment the data or not

#Hardware execution
device = "cpu" # Device to use, either "cuda" or "cpu".

#Debugging/Visualization
filter = false
show_dataset_plot = false # Show dataset plot

# ====================================
# CAMERAS & STAKES Configuration
# ====================================
[cameras.CC1]
total_poles = 3
active_poles = [1, 2, 3]
upside_down = false
enabled = false

[cameras.CC2]
total_poles = 3
active_poles = [1, 2, 3]
upside_down = true
enabled = true

[cameras.CTRL1]
total_poles = 3
active_poles = [1, 2, 3]
upside_down = false
enabled = true

[cameras.CTRL2]
total_poles = 3
active_poles = [1, 2, 3]
upside_down = true
enabled = false

[cameras.S5-CAM-F1A]
total_poles = 3
active_poles = [1, 2, 3]
upside_down = false
enabled = false

[cameras.S5-CAM-F1B]
total_poles = 3
active_poles = [1, 2, 3]
upside_down = false
enabled = false

[cameras.S5-CAM-F2A]
total_poles = 3
active_poles = [1, 3] # pole 2 doesn't have "slant" axis measurements, so set unactive
upside_down = false
enabled = false

[cameras.S5-CAM-F2B]
total_poles = 3
active_poles = [3] # pole 1 and 2 don't have slant axis measurements, so set inactive
upside_down = false
enabled = false

[cameras.S5-CAM-F3]
total_poles = 5
active_poles = [1, 3, 4, 5] # pole 2 not in slant axis measurements, set inactive
upside_down = false
enabled = false

[cameras.S5-F-WX]
total_poles = 2
active_poles = [1, 2]
upside_down = false
enabled = false

[cameras.S6-F-WX]
total_poles = 5
active_poles = [1, 2, 3, 4, 5]
upside_down = false
enabled = false